# Generated by Django 3.1.3 on 2021-12-28 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20211228_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='seller',
            new_name='user',
        ),
    ]
