# Generated by Django 3.1.3 on 2021-12-29 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20211228_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='excerpt',
            new_name='description',
        ),
    ]
