# Generated by Django 3.1.3 on 2021-12-29 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20211229_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='description',
            new_name='excerpt',
        ),
    ]
