# Generated by Django 3.1.3 on 2021-12-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20211229_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
