# Generated by Django 3.1.3 on 2021-12-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20211229_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='price',
            field=models.FloatField(),
        ),
    ]
