# Generated by Django 3.1.3 on 2021-12-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20211230_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
