# Generated by Django 3.1.3 on 2022-01-01 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20211230_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='title',
            new_name='product',
        ),
    ]
