# Generated by Django 3.1.3 on 2022-01-01 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20220101_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='product',
            new_name='title',
        ),
    ]
