# Generated by Django 3.1.3 on 2022-01-01 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20220102_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='title',
            new_name='product',
        ),
    ]
