# Generated by Django 3.1.3 on 2022-01-01 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20220102_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='updated',
        ),
        migrations.AddField(
            model_name='shop',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='shop',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
    ]
