# Generated by Django 4.0.4 on 2022-05-26 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_shop_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='description',
            new_name='overview',
        ),
    ]
